// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: services/perf/proto/contention.proto

// Score-side wire contract for Stage 3.
//
// The ScoreEvent message is what a score.Source produces (one per window
// boundary, paired with the Sample that drove it via sample_id). Mitigation
// systems and any other consumer subscribe to ContentionStream and act on
// the score values.
//
// The score interface is decoupled from any specific producer: the
// source_kind field tells a consumer whether the event came from the
// ONNX predictor, a formula-based scorer, or any other implementation
// registered with the score.Publisher.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreSubscribeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional method-name allow-list. Empty = receive events for all
	// methods. Filters are ANDed with the threshold filters below.
	OnlyMethods []string `protobuf:"bytes,1,rep,name=only_methods,json=onlyMethods,proto3" json:"only_methods,omitempty"`
	// Suppress events where p50_trend_pred < min_p50_trend.
	// Both scores are in [0, 1]; threshold of 0 means no filter.
	MinP50Trend float32 `protobuf:"fixed32,2,opt,name=min_p50_trend,json=minP50Trend,proto3" json:"min_p50_trend,omitempty"`
	// Suppress events where tail_trend_label < min_tail_trend.
	MinTailTrend float32 `protobuf:"fixed32,3,opt,name=min_tail_trend,json=minTailTrend,proto3" json:"min_tail_trend,omitempty"`
}

func (x *ScoreSubscribeReq) Reset() {
	*x = ScoreSubscribeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_perf_proto_contention_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreSubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreSubscribeReq) ProtoMessage() {}

func (x *ScoreSubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_perf_proto_contention_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreSubscribeReq.ProtoReflect.Descriptor instead.
func (*ScoreSubscribeReq) Descriptor() ([]byte, []int) {
	return file_services_perf_proto_contention_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreSubscribeReq) GetOnlyMethods() []string {
	if x != nil {
		return x.OnlyMethods
	}
	return nil
}

func (x *ScoreSubscribeReq) GetMinP50Trend() float32 {
	if x != nil {
		return x.MinP50Trend
	}
	return 0
}

func (x *ScoreSubscribeReq) GetMinTailTrend() float32 {
	if x != nil {
		return x.MinTailTrend
	}
	return 0
}

// ScoreEvent is the score for one window. All score fields are
// continuous values in [0, 1]; higher = more contention.
//
// Producer is the in-pod Gordion scorer (Algorithm 1) which always
// computes the formula outputs (y50_current, tail_trend_label,
// ext_pct_50, ext_pct_90). When the pod additionally runs the ONNX
// predictor (prediction_on = true), p50_trend_pred carries the model's
// predicted next-window y50; otherwise p50_trend_pred = y50_current so
// consumers always have one primary p50 signal regardless of mode.
type ScoreEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SampleId    int64  `protobuf:"varint,1,opt,name=sample_id,json=sampleId,proto3" json:"sample_id,omitempty"` // joins to Sample.sample_id from instrumentation
	TimestampNs int64  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Service     string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	// Primary p50-side signal, [0, 1]. Predicted next-window y50 (ONNX)
	// when prediction_on; the formula's current y50 otherwise.
	P50TrendPred float32 `protobuf:"fixed32,4,opt,name=p50_trend_pred,json=p50TrendPred,proto3" json:"p50_trend_pred,omitempty"`
	// Tail-side signal (formula y90), [0, 1].
	TailTrendLabel float32 `protobuf:"fixed32,5,opt,name=tail_trend_label,json=tailTrendLabel,proto3" json:"tail_trend_label,omitempty"`
	// Stable identifier for the producing configuration: the trainer run
	// config id when prediction_on, the gordion config version otherwise.
	// Mitigation consumers can use this to reject stale streams after a
	// model / config change.
	ModelVersion string `protobuf:"bytes,6,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// Tag for which producer emitted this event ("gordion" for the
	// in-pod scorer; future comparator sources use their own tags). Lets
	// a mitigation differentiate when multiple sources are wired up to
	// the same Publisher.
	SourceKind string `protobuf:"bytes,7,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"`
	// The formula's CURRENT y50 (always populated). Equal to
	// p50_trend_pred when prediction_on is false.
	Y50Current float32 `protobuf:"fixed32,8,opt,name=y50_current,json=y50Current,proto3" json:"y50_current,omitempty"`
	// Extrinsic contention percentages from the intrinsic-curve
	// decomposition: (T~ - D(lambda)) / T~, clamped to [0, 1]. How much
	// of the current p50/p90 shift is attributable to co-located
	// neighbors rather than the service's own load.
	ExtPct_50 float32 `protobuf:"fixed32,9,opt,name=ext_pct_50,json=extPct50,proto3" json:"ext_pct_50,omitempty"`
	ExtPct_90 float32 `protobuf:"fixed32,10,opt,name=ext_pct_90,json=extPct90,proto3" json:"ext_pct_90,omitempty"`
	// True when p50_trend_pred came from the in-pod ONNX predictor.
	PredictionOn bool `protobuf:"varint,11,opt,name=prediction_on,json=predictionOn,proto3" json:"prediction_on,omitempty"`
}

func (x *ScoreEvent) Reset() {
	*x = ScoreEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_perf_proto_contention_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreEvent) ProtoMessage() {}

func (x *ScoreEvent) ProtoReflect() protoreflect.Message {
	mi := &file_services_perf_proto_contention_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreEvent.ProtoReflect.Descriptor instead.
func (*ScoreEvent) Descriptor() ([]byte, []int) {
	return file_services_perf_proto_contention_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreEvent) GetSampleId() int64 {
	if x != nil {
		return x.SampleId
	}
	return 0
}

func (x *ScoreEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *ScoreEvent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ScoreEvent) GetP50TrendPred() float32 {
	if x != nil {
		return x.P50TrendPred
	}
	return 0
}

func (x *ScoreEvent) GetTailTrendLabel() float32 {
	if x != nil {
		return x.TailTrendLabel
	}
	return 0
}

func (x *ScoreEvent) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ScoreEvent) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *ScoreEvent) GetY50Current() float32 {
	if x != nil {
		return x.Y50Current
	}
	return 0
}

func (x *ScoreEvent) GetExtPct_50() float32 {
	if x != nil {
		return x.ExtPct_50
	}
	return 0
}

func (x *ScoreEvent) GetExtPct_90() float32 {
	if x != nil {
		return x.ExtPct_90
	}
	return 0
}

func (x *ScoreEvent) GetPredictionOn() bool {
	if x != nil {
		return x.PredictionOn
	}
	return false
}

var File_services_perf_proto_contention_proto protoreflect.FileDescriptor

var file_services_perf_proto_contention_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x66, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x67, 0x6f, 0x72, 0x64, 0x69, 0x6f, 0x6e, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x80, 0x01, 0x0a, 0x11, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x6e, 0x6c, 0x79, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x35, 0x30, 0x5f, 0x74,
	0x72, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x50,
	0x35, 0x30, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x69, 0x6e, 0x5f, 0x74,
	0x61, 0x69, 0x6c, 0x5f, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0c, 0x6d, 0x69, 0x6e, 0x54, 0x61, 0x69, 0x6c, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x22, 0xfe, 0x02,
	0x0a, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4e, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x35, 0x30, 0x5f, 0x74, 0x72,
	0x65, 0x6e, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c,
	0x70, 0x35, 0x30, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x10,
	0x74, 0x61, 0x69, 0x6c, 0x5f, 0x74, 0x72, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x74, 0x61, 0x69, 0x6c, 0x54, 0x72, 0x65, 0x6e,
	0x64, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x79, 0x35, 0x30, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0a, 0x79, 0x35, 0x30, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x0a, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x63, 0x74, 0x5f, 0x35, 0x30, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x65, 0x78, 0x74, 0x50, 0x63, 0x74, 0x35, 0x30, 0x12, 0x1c, 0x0a, 0x0a, 0x65,
	0x78, 0x74, 0x5f, 0x70, 0x63, 0x74, 0x5f, 0x39, 0x30, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x65, 0x78, 0x74, 0x50, 0x63, 0x74, 0x39, 0x30, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x6e, 0x32, 0x68,
	0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x54, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12,
	0x25, 0x2e, 0x67, 0x6f, 0x72, 0x64, 0x69, 0x6f, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x67, 0x6f, 0x72, 0x64, 0x69, 0x6f, 0x6e,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x63, 0x63, 0x2d, 0x6c, 0x61, 0x62, 0x2f,
	0x64, 0x73, 0x62, 0x5f, 0x68, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x68,
	0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x66, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_perf_proto_contention_proto_rawDescOnce sync.Once
	file_services_perf_proto_contention_proto_rawDescData = file_services_perf_proto_contention_proto_rawDesc
)

func file_services_perf_proto_contention_proto_rawDescGZIP() []byte {
	file_services_perf_proto_contention_proto_rawDescOnce.Do(func() {
		file_services_perf_proto_contention_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_perf_proto_contention_proto_rawDescData)
	})
	return file_services_perf_proto_contention_proto_rawDescData
}

var file_services_perf_proto_contention_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_perf_proto_contention_proto_goTypes = []interface{}{
	(*ScoreSubscribeReq)(nil), // 0: gordion.contention.ScoreSubscribeReq
	(*ScoreEvent)(nil),        // 1: gordion.contention.ScoreEvent
}
var file_services_perf_proto_contention_proto_depIdxs = []int32{
	0, // 0: gordion.contention.ContentionStream.Subscribe:input_type -> gordion.contention.ScoreSubscribeReq
	1, // 1: gordion.contention.ContentionStream.Subscribe:output_type -> gordion.contention.ScoreEvent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_perf_proto_contention_proto_init() }
func file_services_perf_proto_contention_proto_init() {
	if File_services_perf_proto_contention_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_perf_proto_contention_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreSubscribeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_perf_proto_contention_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_perf_proto_contention_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_perf_proto_contention_proto_goTypes,
		DependencyIndexes: file_services_perf_proto_contention_proto_depIdxs,
		MessageInfos:      file_services_perf_proto_contention_proto_msgTypes,
	}.Build()
	File_services_perf_proto_contention_proto = out.File
	file_services_perf_proto_contention_proto_rawDesc = nil
	file_services_perf_proto_contention_proto_goTypes = nil
	file_services_perf_proto_contention_proto_depIdxs = nil
}
