// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: services/perf/proto/contention.proto

// Score-side wire contract for Stage 3.
//
// The ScoreEvent message is what a score.Source produces (one per window
// boundary, paired with the Sample that drove it via sample_id). Mitigation
// systems and any other consumer subscribe to ContentionStream and act on
// the score values.
//
// The score interface is decoupled from any specific producer: the
// source_kind field tells a consumer whether the event came from the
// ONNX predictor, a formula-based scorer, or any other implementation
// registered with the score.Publisher.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ContentionStream_Subscribe_FullMethodName = "/gordion.contention.ContentionStream/Subscribe"
)

// ContentionStreamClient is the client API for ContentionStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentionStreamClient interface {
	// Subscribe is a server-streaming RPC. The server sends one ScoreEvent
	// per window boundary, applying optional client-side filters from the
	// request. Per-subscriber drop-on-overflow if the client falls behind.
	Subscribe(ctx context.Context, in *ScoreSubscribeReq, opts ...grpc.CallOption) (ContentionStream_SubscribeClient, error)
}

type contentionStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewContentionStreamClient(cc grpc.ClientConnInterface) ContentionStreamClient {
	return &contentionStreamClient{cc}
}

func (c *contentionStreamClient) Subscribe(ctx context.Context, in *ScoreSubscribeReq, opts ...grpc.CallOption) (ContentionStream_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &ContentionStream_ServiceDesc.Streams[0], ContentionStream_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &contentionStreamSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ContentionStream_SubscribeClient interface {
	Recv() (*ScoreEvent, error)
	grpc.ClientStream
}

type contentionStreamSubscribeClient struct {
	grpc.ClientStream
}

func (x *contentionStreamSubscribeClient) Recv() (*ScoreEvent, error) {
	m := new(ScoreEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContentionStreamServer is the server API for ContentionStream service.
// All implementations must embed UnimplementedContentionStreamServer
// for forward compatibility
type ContentionStreamServer interface {
	// Subscribe is a server-streaming RPC. The server sends one ScoreEvent
	// per window boundary, applying optional client-side filters from the
	// request. Per-subscriber drop-on-overflow if the client falls behind.
	Subscribe(*ScoreSubscribeReq, ContentionStream_SubscribeServer) error
	mustEmbedUnimplementedContentionStreamServer()
}

// UnimplementedContentionStreamServer must be embedded to have forward compatible implementations.
type UnimplementedContentionStreamServer struct {
}

func (UnimplementedContentionStreamServer) Subscribe(*ScoreSubscribeReq, ContentionStream_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedContentionStreamServer) mustEmbedUnimplementedContentionStreamServer() {}

// UnsafeContentionStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentionStreamServer will
// result in compilation errors.
type UnsafeContentionStreamServer interface {
	mustEmbedUnimplementedContentionStreamServer()
}

func RegisterContentionStreamServer(s grpc.ServiceRegistrar, srv ContentionStreamServer) {
	s.RegisterService(&ContentionStream_ServiceDesc, srv)
}

func _ContentionStream_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScoreSubscribeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContentionStreamServer).Subscribe(m, &contentionStreamSubscribeServer{stream})
}

type ContentionStream_SubscribeServer interface {
	Send(*ScoreEvent) error
	grpc.ServerStream
}

type contentionStreamSubscribeServer struct {
	grpc.ServerStream
}

func (x *contentionStreamSubscribeServer) Send(m *ScoreEvent) error {
	return x.ServerStream.SendMsg(m)
}

// ContentionStream_ServiceDesc is the grpc.ServiceDesc for ContentionStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentionStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gordion.contention.ContentionStream",
	HandlerType: (*ContentionStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ContentionStream_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/perf/proto/contention.proto",
}
