// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: services/perf/proto/instrumentation.proto

// Sample-side wire contract for Stage 3.
//
// The Sample message mirrors the in-process Go struct produced every
// WINDOW_INTERVAL_MS by services/perf/windowed_sampler.go::takeSample
// (perf counters via perf_event_open + MSR-derived freq utilization +
// gRPC interceptor timing aggregates).
//
// In-binary subscribers (e.g. a score.Source running in the same Go
// binary) consume the native Go struct directly; this proto is paid only
// when an external client subscribes to InstrumentationStream over gRPC.
//
// This is the canonical wire contract for the instrumentation ->
// score-source boundary. Any language can implement an
// InstrumentationStream consumer.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InstrumentationStream_Subscribe_FullMethodName = "/gordion.instrumentation.InstrumentationStream/Subscribe"
)

// InstrumentationStreamClient is the client API for InstrumentationStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstrumentationStreamClient interface {
	// Subscribe is a server-streaming RPC. The server sends one Sample per
	// window boundary (10 Hz at the default WINDOW_INTERVAL_MS=100). The
	// server applies per-subscriber drop-on-overflow if the client falls
	// behind.
	Subscribe(ctx context.Context, in *SampleSubscribeReq, opts ...grpc.CallOption) (InstrumentationStream_SubscribeClient, error)
}

type instrumentationStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewInstrumentationStreamClient(cc grpc.ClientConnInterface) InstrumentationStreamClient {
	return &instrumentationStreamClient{cc}
}

func (c *instrumentationStreamClient) Subscribe(ctx context.Context, in *SampleSubscribeReq, opts ...grpc.CallOption) (InstrumentationStream_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &InstrumentationStream_ServiceDesc.Streams[0], InstrumentationStream_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &instrumentationStreamSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InstrumentationStream_SubscribeClient interface {
	Recv() (*Sample, error)
	grpc.ClientStream
}

type instrumentationStreamSubscribeClient struct {
	grpc.ClientStream
}

func (x *instrumentationStreamSubscribeClient) Recv() (*Sample, error) {
	m := new(Sample)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InstrumentationStreamServer is the server API for InstrumentationStream service.
// All implementations must embed UnimplementedInstrumentationStreamServer
// for forward compatibility
type InstrumentationStreamServer interface {
	// Subscribe is a server-streaming RPC. The server sends one Sample per
	// window boundary (10 Hz at the default WINDOW_INTERVAL_MS=100). The
	// server applies per-subscriber drop-on-overflow if the client falls
	// behind.
	Subscribe(*SampleSubscribeReq, InstrumentationStream_SubscribeServer) error
	mustEmbedUnimplementedInstrumentationStreamServer()
}

// UnimplementedInstrumentationStreamServer must be embedded to have forward compatible implementations.
type UnimplementedInstrumentationStreamServer struct {
}

func (UnimplementedInstrumentationStreamServer) Subscribe(*SampleSubscribeReq, InstrumentationStream_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedInstrumentationStreamServer) mustEmbedUnimplementedInstrumentationStreamServer() {}

// UnsafeInstrumentationStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstrumentationStreamServer will
// result in compilation errors.
type UnsafeInstrumentationStreamServer interface {
	mustEmbedUnimplementedInstrumentationStreamServer()
}

func RegisterInstrumentationStreamServer(s grpc.ServiceRegistrar, srv InstrumentationStreamServer) {
	s.RegisterService(&InstrumentationStream_ServiceDesc, srv)
}

func _InstrumentationStream_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SampleSubscribeReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InstrumentationStreamServer).Subscribe(m, &instrumentationStreamSubscribeServer{stream})
}

type InstrumentationStream_SubscribeServer interface {
	Send(*Sample) error
	grpc.ServerStream
}

type instrumentationStreamSubscribeServer struct {
	grpc.ServerStream
}

func (x *instrumentationStreamSubscribeServer) Send(m *Sample) error {
	return x.ServerStream.SendMsg(m)
}

// InstrumentationStream_ServiceDesc is the grpc.ServiceDesc for InstrumentationStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstrumentationStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gordion.instrumentation.InstrumentationStream",
	HandlerType: (*InstrumentationStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _InstrumentationStream_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/perf/proto/instrumentation.proto",
}
