
apiVersion: v1
kind: Service
metadata:
  name: shipping-db-pod
spec:
  selector:
    blueprint.service: shipping-db-pod
  ports:
  
    - name: shipping-db-addr
      port: 27017
      targetPort: 27017
