disabled: false
reporter:
  logSpans: false
  localAgentHostPort: "jaeger-agent:6831"
#  CollectorEndpoint: "http://jaeger-collector:14268/api/traces"
  queueSize: 1000000
  bufferFlushInterval: 10
sampler:
  type: "probabilisitc"
  param: 0.01