
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-pod
  labels:
    blueprint.service: shipping-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      blueprint.service: shipping-pod
  template:
    metadata:
      name: shipping-pod
      labels:
        blueprint.service: shipping-pod
    spec:
      containers:
      
        - name: shipping-ctr
          image: docclabgroup/sockshop_shipping_ctr
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "2"
              memory: "1Gi"
            limits:
              cpu: "3"
              memory: "2Gi"
          env:
            - name: SHIPPING_SERVICE_GRPC_BIND_ADDR
              value: "0.0.0.0:12345"
            - name: SHIPPING_SERVICE_GRPC_DIAL_ADDR
              value: "localhost:12345"
            - name: SHIPPING_DB_DIAL_ADDR
              value: "shipping-db-pod:27017"
            - name: ZIPKIN_DIAL_ADDR
              value: "zipkin-pod:9411"
          ports:
            - containerPort: 12345
      restartPolicy: Always
      hostname: shipping-pod
