
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-pod
  labels:
    blueprint.service: order-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      blueprint.service: order-pod
  template:
    metadata:
      name: order-pod
      labels:
        blueprint.service: order-pod
    spec:
      containers:
      
        - name: order-ctr
          image: docclabgroup/sockshop_order_ctr
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "2"
              memory: "1Gi"
            limits:
              cpu: "3"
              memory: "2Gi"
          env:
            - name: ORDER_SERVICE_GRPC_BIND_ADDR
              value: "0.0.0.0:12345"
            - name: ORDER_DB_DIAL_ADDR
              value: "order-db-pod:27017"
            - name: CART_SERVICE_GRPC_DIAL_ADDR
              value: "cart-pod:12345"
            - name: PAYMENT_SERVICE_GRPC_DIAL_ADDR
              value: "payment-pod:12345"
            - name: SHIPPING_SERVICE_GRPC_DIAL_ADDR
              value: "shipping-pod:12345"
            - name: USER_SERVICE_GRPC_DIAL_ADDR
              value: "user-pod:12345"
            - name: ZIPKIN_DIAL_ADDR
              value: "zipkin-pod:9411"
          ports:
            - containerPort: 12345
      restartPolicy: Always
      hostname: order-pod
