
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-pod
  labels:
    blueprint.service: payment-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      blueprint.service: payment-pod
  template:
    metadata:
      name: payment-pod
      labels:
        blueprint.service: payment-pod
    spec:
      containers:
      
        - name: payment-ctr
          image: docclabgroup/sockshop_payment_ctr
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "2"
              memory: "1Gi"
            limits:
              cpu: "3"
              memory: "2Gi"
          env:
            - name: PAYMENT_SERVICE_GRPC_BIND_ADDR
              value: "0.0.0.0:12345"
            - name: ZIPKIN_DIAL_ADDR
              value: "zipkin-pod:9411"
          ports:
            - containerPort: 12345
      restartPolicy: Always
      hostname: payment-pod
