
apiVersion: v1
kind: Service
metadata:
  name: payment-pod
spec:
  selector:
    blueprint.service: payment-pod
  ports:
  
    - name: payment-service-grpc-addr
      port: 12345
      targetPort: 12345
