
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-pod
  labels:
    blueprint.service: catalogue-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      blueprint.service: catalogue-pod
  template:
    metadata:
      name: catalogue-pod
      labels:
        blueprint.service: catalogue-pod
    spec:
      containers:
      
        - name: catalogue-ctr
          image: docclabgroup/sockshop_catalogue_ctr
          imagePullPolicy: Always
          env:
            - name: CATALOGUE_SERVICE_GRPC_BIND_ADDR
              value: "0.0.0.0:12345"
            - name: CATALOGUE_DB_DIAL_ADDR
              value: "catalogue-db-pod:3306"
            - name: ZIPKIN_DIAL_ADDR
              value: "zipkin-pod:9411"
          ports:
            - containerPort: 12345
      restartPolicy: Always
      hostname: catalogue-pod
