
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-pod
  labels:
    blueprint.service: cart-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      blueprint.service: cart-pod
  template:
    metadata:
      name: cart-pod
      labels:
        blueprint.service: cart-pod
    spec:
      containers:
      
        - name: cart-ctr
          image: docclabgroup/sockshop_cart_ctr
          imagePullPolicy: Always
          env:
            - name: CART_SERVICE_GRPC_BIND_ADDR
              value: "0.0.0.0:12345"
          ports:
            - containerPort: 12345
      restartPolicy: Always
      hostname: cart-pod
